fts/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('home.urls'), name='home'),
    url(r'^mecanicos/', include('mecanicos.urls')),
    url(r'^talleres/', include('talleres.urls'), name='talleres'),
    url(r'^', include('comentarios.urls')),
    url(r'^encuestas/', include('polls.urls'), name='encu'),
    url(r'^admin/', admin.site.urls),
    url('', include('social_django.urls', namespace='social')),
]

home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^phpinfo/$', views.php_view, name='php_view'),
    url(r'^login/$', views.enter, name='enter'),
    url(r'^logout/$', views.log_out, name='log_out'),
    url(r'^aboutfts/$', views.about_fts, name='about_fts'),
]

mecanicos/urls.py
from django.conf.urls import url

from . import views

app_name = 'mecanicos'

urlpatterns = [
    url(r'^$', views.index, name='index'),
   # url(r'^/registro/$', views.vote, name='registro'),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    # notice the 'name' value as called by the {% url %} template tag
    # ex: /polls/
    #url(r'^$', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    # if i add specifics here now i dont need to fix href on "index.html" template
    #url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    #url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),    
]

talleres/urls.py
from django.conf.urls import url
from .views import (
    TalleresList,
    TalleresDetail,
    TallerCreation,
    TallerUpdate,
    TallerDelete,
    cargar_taller
)

app_name = 'talleres'
urlpatterns = [
    url(r'^talleres/$', TalleresList.as_view(), name='talleres_view'),
    url(r'cargar-contenido-taller/(?P<id>\d+)$', cargar_taller),
    url(r'^(?P<pk>\d+)$', TalleresDetail.as_view(), name='TalleresDetail'),
    url(r'^nuevo$', TallerCreation.as_view(), name='newTaller'),
    url(r'^editar/(?P<pk>\d+)$', TallerUpdate.as_view(), name='editTaller'),
    url(r'^borrar/(?P<pk>\d+)$', TallerDelete.as_view(), name='deleteTaller')
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

import os

# Create your views here.
# from django.http import HttpResponse
# from django.shortcuts import render_to_response
# from django.template import RequestContext


@login_required
def index(request):
    # return HttpResponse("Hello, world. You're at the home page.")
    # return render_to_response('home/index.html', context_instance=RequestContext(request))
    return render(request, 'home/index.html', {'username': request.user.username})

""""
class IndexList(ListView):
    template_name = 'home/index.html'
    model = User
    context_object_name = 'username'
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        c = super(IndexList, self).get_context_data(**kwargs)
        # add the request to the context
        c.get( self, User.username)
        return c
"""

@login_required
def php_view(request):
    # template_name = 'home/display-php.html'
    info_php_cmd = 'php home/static/home/info.php'
    fp = os.popen(info_php_cmd)
    info_php_list = fp.readlines()
    fp.close()
    # context is a dictionary mapping template
    context = {
        'info_php_list': info_php_list,
    }
    return render(request, 'home/display-php.html', context)


def about_fts(request):
    return render(request, 'home/aboutFts.html')


def enter(request):
    return render(request, 'home/login.html')


#@login_required
#def home(request):
#    return render(request, 'home/index.html', {'username': request.user.username})


def log_out(request):
    logout(request)
    return redirect('home:enter')

home/templates/home/aboutFts.html
{% extends "home/baseAboutFts.html" %}

{% block page_title %}
    About Free Time Software
{% endblock %}

{% block content %}
    <div id="wrapper">
        <div id="header"></div>
        <div id="bg"></div>
    </div>

    <div id="main-content">
        <div id="left-column">
            <div id="logo">
                Freetime Softwate Home Page
                <h2>Que decir que decir que decir</h2>
                <p> {% load static %}
                    <img src="{% static 'home/images/FreeTimeSoftware.png' %}"
                         width="139"
                         height="150"
                         style="margin: 0 10px 10px 0;float:left;" />
                    <em>Que decir que decir que decir Que decir que decir que decir</em><br/>
                    <em>Que decir que decir que decir Que decir que decir que decir
                        Que decir que decir que decir</em> <br/>
                    <em>Que decir que decir que decir Que decir que decir que decir
                        Que decir que decir que decir</em> <br/>
                    <em>Que decir que decir que decir</em><br/>
                </p>
            </div>
            <div class="sidebar">
                <h3>Ejemplo loco</h3>
                <p>Ahhhhhhhhhhhhhhhhh</p>
            </div>
        </div>
    </div>
    <div id="footer">
        Layout adapted from <a href="http://www.web-designers-directory.org/"
                               target="_blank">Web Designers' Directory</a>.
    </div>
{% endblock %}

home/templates/home/baseAboutFts.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block page_title %} {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}" />
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

home/templates/home/baseIndex.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- jQuery library -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> -->
    <!-- Latest compiled JavaScript -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
    <title>{% block page_title %} {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}" />
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

<!--
<html lang="en">
  <head>
    <meta name="google-signin-scope" content="profile email">
    <meta name="google-signin-client_id" content="xx.apps.googleusercontent.com">
    <script src="https://apis.google.com/js/platform.js" async defer></script>
  </head>
  <body>
    <div class="g-signin2" data-onsuccess="onSignIn" data-theme="dark"></div>
    <script>
      function onSignIn(googleUser) {
        // Useful data for your client-side scripts:
        var profile = googleUser.getBasicProfile();
        console.log("ID: " + profile.getId()); // Don't send this directly to your server!
        console.log('Full Name: ' + profile.getName());
        console.log('Given Name: ' + profile.getGivenName());
        console.log('Family Name: ' + profile.getFamilyName());
        console.log("Image URL: " + profile.getImageUrl());
        console.log("Email: " + profile.getEmail());

        // The ID token you need to pass to your backend:
        var id_token = googleUser.getAuthResponse().id_token;
        console.log("ID Token: " + id_token);
      };
    </script>
  </body>
</html>
-->

home/templates/home/baseLogin.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Free Time Sofware Login</title>
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
</head>
<body>
	<div class="container theme-showcase">
		<div class="jumbotron">
			{% block content %}
			{% endblock content %}
		</div>
	</div>
</body>
</html>

home/templates/home/display-php.html
<script src="https://apis.google.com/js/platform.js" async defer></script>

{% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'home/css/stylePhp.css' %}" />

{% if info_php_list %}
    <ul>
        {% for line in info_php_list %}
         <li><a>{{ line }} </a></li>
        {% endfor %}
    </ul>
{% endif %}

home/templates/home/index.html
{% extends "home/baseIndex.html" %}

{% block page_title %}
    FreeTime Software logued as {{username}}
{% endblock %}

{% block content %}
    <div class="header"> {% load static %}
        <h1>FreeTime Software - Hola {{username}}!
            <img src="{% static 'home/images/FreeTimeSoftware.png' %}"
                 width="55"
                 height="55"
                 style="margin: 0 10px 10px 0;float:right;" /></h1>
        <h2 style="font-size: 14px">Mecanet - Market Cental</h2>
    </div>
    <ul>
        <li><a class="active" href="{% url 'home:about_fts' %}" target="iframe_a">Home</a></li>
        <li><a href="http://localhost/info.php" target="iframe_a">Noticias</a></li>
        <li><a href="{% url 'talleres:talleres_view' %}" target="iframe_a" >Talleres</a> </li>
        <li class="dropdown" >
            <a class="dropbtn" href="{% url 'mecanicos:index' %}" target="iframe_a">Servicios</a>
            <div class="dropdown-content">
                <a href="http://httpd.apache.org/docs/2.0/misc/tutorials.html"
                   target="iframe_a">Tutorial</a>
                <a href="http://httpd.apache.org/docs/current/mod/mod_unique_id.html"
                   target="iframe_a">Apache mod</a>
                <a href="http://httpd.apache.org/docs/2.4/mod/core.html#serversignature"
                   target="iframe_a">Server Signature</a>
            </div>
        </li>
        <li><a href="{% url 'home:php_view' %}"
               target="iframe_a" >Perfil</a> </li>
        <li><a href="http://php.net/manual/es/tutorial.firstpage.php"
               target="iframe_a">Contacto</a></li>
        <li><a href="https://dashfdj.wordpress.com/"
               target="iframe_a">Blog</a></li>
        <li><a href="{% url 'home:about_fts' %}" target="iframe_a">About</a></li>
        <li><a href="{% url 'polls:index' %}"
               target="iframe_a" >Encuestas</a></li>
        <li><a href="{% url 'home:log_out' %}" >Log out</a></li>
        <li class="dropdown" style="float:right;">
            <a class="dropbtn" href="#language">Language</a>
            <div class="dropdown-content">
                <a href="#">Espa&ntilde;ol</a>
                <a href="#">English</a>
            </div>
        </li>
    </ul>
    <iframe width="100%" height=700px src="{% url 'home:about_fts' %}" name="iframe_a"></iframe>
    <div class="box">
        <ul>
            <li><em class="find-us">Encontranos en:</em><a href="http://facebook.com" target="_blank">Facebook</a></li>
            <li><a href="http://twitter.com" target="_blank">Twitter </a></li>
            <li><a href="http://tumblr.com" target="_blank">Tumblr</a></li>
            <li><a href="http://pinterest.com" target="_blank">Pinterest</a></li>
        </ul>
        <div id="footer">
            <center>
                Copyright &copy; 2017 FreeTime Software. All rights reserved.<br/>
                Powered by Django, Python, MySQL, Apache, Nginx, GitHub,
                Amazon Web Services, Oracle VM VirtualBox and Docker
            </center>
        </div>
    </div>
{% endblock %}

home/templates/home/login.html
{% extends "home/baseLogin.html" %}

{% block content %}
	<section>
        {% load static %}
		<h1>Free Time Software Login
			<img src="{% static 'home/images/FreeTimeSoftware.png' %}"
				 width="139"
				 height="150"
				 style="margin: 0 10px 10px 0;float:left;" />
		</h1>
		<p>
			<a href="{% url 'social:begin' 'twitter' %}" class="btn btn-info btn-lg" role="button">Twitter</a>
			<a href="{% url 'social:begin' 'facebook' %}" class="btn btn-primary btn-lg" role="button">Facebook</a>
            <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-info btn-lg" role="button">Google</a>
		</p>
	</section>
{% endblock content %}